Traceback (most recent call last):
  File "mpi_samplefull.py", line 3, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "mpi_samplefull.py", line 3, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[48174,1],0]
  Exit code:    1
--------------------------------------------------------------------------
